name: mgi_final
description: "A car dealership managegement application"
publish_to: 'none'
version: 0.1.0

authors:
  - Bob Paul <paul0375@algonquinlive.com>
  - Peter Stainforth <stai0029@algonquinlive.com>
  - Melbin Benny Thomas <thom1654@algonquinlive.com>
  - Yanbo Ma <ma000166@algonquinlive.com>

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  floor: ^1.4.0
  sqflite: ^2.0.0+4
  encrypted_shared_preferences: ^3.0.1
  google_fonts: ^5.0.0
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.1.2
  floor_generator: ^1.4.0

flutter:
  uses-material-design: true
